name: Release

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  linux:
    name: Ubuntu build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Install conan
        run: pip install conan

      - name: Run conan
        run: ./build.sh

      - name: Copy file
        run: cp ${{ github.workspace }}/build/stock_manager ${{ github.workspace }}/stock_manager-linux

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            ${{ github.workspace }}/stock_manager-ubuntu-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows:
    name: Windows build
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Install conan
        run: pip install conan

      - name: Run conan
        run: ./build.sh

      - name: Copy file
        run: cp ${{ github.workspace }}/build/stock_manager.exe ${{ github.workspace }}/stock_manager-win.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            ${{ github.workspace }}/stock_manager-win.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
